name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - run: |
        if [[ "${{secrets.DOCKER_HUB_REPOSITORY}}" == "" ]]; then
          echo The secrets.DOCKER_HUB_REPOSITORY does not exist
        else
          echo The secrets.DOCKER_HUB_REPOSITORY exists
        fi    
    
    - run: |
        if [[ "${{secrets.DOCKER_HUB_USERNAME}}" == "" ]]; then
          echo The secrets.DOCKER_HUB_USERNAME does not exist
        else
          echo The secrets.DOCKER_HUB_USERNAME exists
        fi      
        
    - run: |
        if [[ "${{secrets.DOCKER_HUB_TOKEN}}" == "" ]]; then
          echo The secrets.DOCKER_HUB_TOKEN does not exist
        else
          echo The secrets.DOCKER_HUB_TOKEN exists
        fi             
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.Api --tag to-do:$(date +%s)

    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ secrets.DOCKER_HUB_REPOSITORY }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
